### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by netsvetaev** [psychedelicious/sdui#1]
Hi! 
I started making a simple gui design for [lstein](https://github.com/lstein) fork of SD, then realized that you already do gui on react. I was mostly focused on current implementation of UI and also made a mobile template for it, but seems like your version on react is better to build it on. [Here is my thread with templates](https://github.com/lstein/stable-diffusion/issues/379#issue-1361306188).
Maybe my work will be helpful?

**Comment by psychedelicious** [comment]
Hi @netsvetaev 

Your design looks great! I've just moved development to a fork of the main repo as I work on an API in conjunction with front end: https://github.com/psychedelicious/stable-diffusion/tree/api/

Discussion taking place here: https://github.com/lstein/stable-diffusion/discussions/336

My plan is to get the desktop version ready for a release and then work on tablet/mobile layouts. I've never worked from a mockup (well, unless you count pencil scribblings on paper hah) so I'd be interested in trying something new if you want to contribute here. Also very happy for contributions to the desktop version - I'm just iterating as I go with more of a general vision.
